lightninglabs/lightning-terminal

app/src/api/loop.ts
Currently, `MaxSwapRoutingFee` is set to 2% of the `SwapFee` instead of 2% of the swap `Amount`. This can cause Loop Out off-chain payments to fail more often than they should because the max fee is set very low.
=> loop: increase max swap routing fee

app/src/__tests__/components/history/HistoryPage.spec.tsx, app/src/__tests__/components/loop/LoopPage.spec.tsx, app/src/assets/icons/arrow-down.svg, app/src/assets/icons/arrow-up.svg, app/src/assets/icons/slash.svg, app/src/components/base/icons.tsx, app/src/components/common/SortableHeader.tsx, app/src/components/history/HistoryRow.tsx, app/src/components/loop/ChannelRow.tsx, app/src/i18n/locales/en-US.json, app/src/store/models/channel.ts, app/src/store/models/swap.ts, app/src/store/stores/channelStore.ts, app/src/store/stores/settingsStore.ts, app/src/store/stores/swapStore.ts, app/src/types/state.ts
Closed #86 
This PR adds the ability to manually sort the channel and history lists by clicking on the column headers.
1. Go to the Terminal page
1. Click on the column headers (click twice on the same header to change the direction)
1. Confirm the channels are sorting in the correct order
1. Go to the Loop History page
1. Clicking on the column headers
1. Confirm the loops are sorting in the correct order
=> add sorting of the channel and history lists

README.md, doc/config-lnd-integrated.md, go.mod, go.sum, terminal.go
This PR contains four independent changes that are too small to justify their own PRs:
1. Update Pool to version `v0.3.3-alpha`.
2. Mention the new `lnd-mode=integrated` flag in the docs where we describe the upgrade process from pre-0.3.0 versions.
3. Fix a connection timeout issue that caused long-running calls or streaming responses to be cut off after 10 seconds.
4. Bump versions in README.
Fixes #140, fixes #144.
=> multi: update pool, fix docs, fix timeout issue

Dockerfile
https://groups.google.com/g/golang-announce/c/NpBGTTmKzpM/m/fLguyiM2CAAJ
Geth has made this change a high priority. Unsure if LND is affected. I have built LIT docker with 1.15.5 and it seems to run ok.  (havent tested lnd, pool, loop) - running to a remote lnd.
=> Update golang to 1.15.5 for security update

.github/workflows/docker.yml, Makefile, dev.Dockerfile, doc/compile.md
We add a new production `Dockerfile` and a GitHub workflow that is triggered whenever a new version tag is
pushed. It will trigger a docker image build for that version and automatically push it to the specified repo.
For this to work, the GitHub repository needs the following two secrets to be configured:
```
DOCKER_USERNAME: <the user to log into Docker Hub>
DOCKER_API_KEY: <an API key generated by Docker Hub for the above user>
```
=> docker+GitHub: add production Dockerfile and build automatically on tag push

.gitattributes, .github/workflows/main.yml, app/scripts/build-protos.js, app/src/types/generated/lnd_pb.d.ts, app/src/types/generated/lnd_pb.js, app/src/types/generated/lnd_pb_service.d.ts, app/src/types/generated/lnd_pb_service.js, app/src/types/generated/loop_pb.d.ts, app/src/types/generated/loop_pb.js, doc/compile.md, proto/lnd.proto, proto/loop.proto
As a follow up to #158 which removed the dependency on `protoc` at the machine level to compile from source, this PR makes a few updates:
- update the compile.md doc removing the `protoc` dependency
- update `yarn protos` script to download protos from github instead of needing to do this manually
- update the compile.md with instructions to compile the protos whenever we update the `lnd` and `loop` versions
- update the proto files to match the `lnd` and `loop` versions currently included with Terminal
- fix generated code being included in GitHub language stats
=> Update protos build script

.github/workflows/docker.yml, README.md, app/scripts/build-protos.js, doc/compile.md, go.mod, go.sum
With this PR we prepare to release a minor version of LiT that contains the following changes:
- Only build docker images for 64bit ARM, remove the 32bit target to be in sync with the `lnd` images.
- Update Loop to `v0.11.2-beta`.
- Extract `lnd` and `poold` versions from `go.mod` when compiling proto files.
=> Prepare for LiT v0.3.3-alpha

config.go, terminal.go
Fixes https://github.com/lightninglabs/lightning-terminal/issues/162.
For uses of LiT through Tor connections that add their own layer of
transport security, it doesn't make sense to add TLS on top. We
therefore allow running an additional HTTP only listener.
@justinpobrien requesting review from you as well because this contains a potential security footgun if used improperly. Does the flag name `--insecure-httplisten` convey the danger of enabling this sufficiently?
=> add insecure HTTP only listener option

app/src/components/tour/WelcomeStep.tsx
Closes #166 
Updated the broken link in the tour's first step to point to the walkthrough in the GitBook docs website.
=> tour: fix walkthrough link

.github/workflows/docker.yml
To avoid leaking any sensitive information like Docker Hub credentials
because of compromised actions repositories, we use our own, vendored
actions for all steps that potentially touch sensitive information.
=> GitHub: use vendored actions for steps with sensitive info

doc/testing.md, rpc_proxy.go, terminal.go
The call flow diagram wasn't accurate what lead to an incorrect
assumption in the last PR.
In integrated mode, lnd spins up its gRPC server as the main entry point
and the other daemons need to hook into it.
To make sure bugs like this don't happen anymore, we also add a test scenario/protocol document that covers all the existing use cases.
=> Fix main lnd port usage for daemons in lnd-mode=integrated

app/src/components/pool/account/AccountSummary.tsx, app/src/i18n/locales/en-US.json, app/src/store/models/account.ts
This PR just makes a couple minor updates to the account section:
1. Display a button to close the account. Previously, the user needed to wait until the account was about to expire to close it. Now, the account can be closed at any time.
2. Display the account/trader key in the account section as this is useful when troubleshooting Pool account issues.
=> pool+accounts: minor account section updates

app/src/__tests__/components/pool/AccountSection.spec.tsx, app/src/components/pool/account/NoAccount.tsx, app/src/i18n/locales/en-US.json, app/src/store/views/accountSectionView.ts
When the `lnd` node has no open channels, an account cannot be opened due to an inevitable LSAT payment failure. If the account creation is attempted, the resulting error message is also very cryptic.
This PR just adds a notice message when the node doesn't have any channels, stating "Your node must already have open channels before you can fund your Pool account.". It also disables the "Open an Account" button in this case as well.
=> pool+accounts: display warning if node has no channels

app/src/store/stores/swapStore.ts
Closes #187 
This PR fixes a small bug which prevented the user from being able to dismiss failed swaps in the Processing Loops section. When clicking on the Dismiss icon, nothing would happen.
1. Since the processing swaps list only displays swaps completed in the past 5 minutes, you'll first need to perform a swap. 2. Change the swap's `state` to failed by running `store.swapStore.sortedSwaps[0].state = 4` in the browser console
3. Click on the Expand icon in the Loop History tile to open the Processing Loops section 
4. Click on the Gray "X" icon to dismiss the failed Loop
5. Confirm the failed Loop disappears
=> loop: fix dismiss swap icon not working

config.go
Partially reverts c917e91f and fixes #195: The default remote lnd admin
macaroon path we added in c917e91f was a mistake since by default that
value isn't set until we call lnd.ValidateConfig() which we never do in
the remote mode.
We fix this by providing a sane default value for the admin macaroon
again.
=> config: fix empty default remote lnd admin mac path

app/src/components/common/FormInputNumber.tsx, app/src/util/formatters.ts
This PR fixes an issue where the number inputs in the Pool order form would truncate values incorrectly when the browser's language is not English.
=> pool+orders: fix number input being truncated

go.sum, tools.go
With go 1.16 something changed in how the content of go.sum is
calculated. The "go mod tidy" command now removes dependencies for
packages that aren't directly referenced through the main package.
Therefore if we compile another binary (such as the CLI binaries we ship
together with LiT) some of their dependencies might have been pruned
from go.sum. To avoid that, we add dummy imports for those packages
under a build tag that we don't actually use. The "tools" tag seems to
be the idiomatic tag for such tooling depencencies.
Thanks for reporting this, @jamaljsr!
=> mod+tools: add dummy import for CLI dependencies

config.go, rpc_proxy.go, terminal.go
Fixes #213.
Fixes #214.
This PR adds a new top level flag (`--enablerest`) or config item (`enablerest=true`) that enables REST calls to be made to the main HTTP(S) listener.
With this the main HTTP(S) listener can now handle native gRPC, grpc-web, REST and static file requests for all daemons (lnd, faraday, loop, pool) independent of whether they run in integrated or remote mode.
Lightning Terminal becomes the ultimate lnd&friends reverse proxy.
=> Add full REST support

README.md, app/scripts/build-protos.js, config.go, go.mod, go.sum
Replaces #238.
Fixes some small leftover issues after #226 was merged.
=> Cleanup after upgrade to lnd v0.13.0-beta

go.mod, go.sum
Loop in was failing with `Swap error: EOF` because we didn't pull in the
latest version of lndclient that properly handles the single invoice
subscription EOF that is being returned with lnd 0.13.x.
=> mod: bump lndclient version to fix loop in

terminal.go
I was getting the below errors when trying to use LiT:
```
$ litd --uipassword=test1234 --remote.lnd.rpcserver=node:10009 --remote.lnd.tlscertpath=~/.lnd/node/tls.cert  --remote.lnd.macaroonpath=~/.lnd/node/admin.macaroon
2021-08-13 08:57:20.611 [INF] LITD: Dialing lnd gRPC server at node:10009
2021-08-13 08:57:20.627 [INF] LITD: Listening for http_tls on: 127.0.0.1:8443
2021-08-13 08:57:25.622 [WRN] GRPC: grpc: addrConn.createTransport failed to connect to {node:10009  <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp: i/o timeout". Reconnecting...
----------------------------------------------------------
Lightning Terminal (LiT) by Lightning Labs
Operating mode      remote
Node status         online
Alias               node
Version …
```
=> rpc: Increase the default connection timeout to LND

README.md
We create a new minor release for the UI bug fixes and dependency
updates that were merged recently, as well as a fux to the default
macaroon path handling.
We cannot yet update any of the bundled libraries because of their
dependency on lnd v0.14.0.
=> README: update version to v0.5.1-alpha

.github/workflows/docker.yml, Dockerfile, Makefile, doc/custom-path.md, doc/example-nginx.conf, terminal.go
Creates a secondary docker image with the tag `:v0.x.y-alpha-path-prefix` that is auto built and pushed to Docker Hub and assumes that LiT is being run under the custom URL path `/lit`.
An example nginx configuration for setting up a reverse proxy that responds to both LiT `grpc-web` requests and native `lnd` gRPC requests under the same domain (and therefore TLS cert) is included. This mainly addresses setups like BTCPayServer (see https://github.com/btcpayserver/btcpayserver-docker/pull/512).
=> docker: create and push secondary image with path prefix

config.go, rpc_proxy.go, subserver_permissions.go, terminal.go
Replaces #269.
I started reviewing #269 and noticed a few things that could be simplified.
Taking over the PR to speed things up and hopefully get this in with the next major LiT release that also includes `lnd v0.14.0`.
=> Stateless integrated mode

README.md, app/src/components/connect/ConnectPage.tsx, app/src/components/layout/NavMenu.tsx, app/src/store/views/appView.ts, rpc_proxy.go, terminal.go
This is a follow-up commit that fixes an issue introduced with stateless
init where an error would be interpreted incorrectly.
This will bump the version in the README to `v0.6.1-alpha`.
=> Fix error handling with stateless init

app/src/store/views/appView.ts
Closes #299 
This PR is a small fix to the "Lightning Node Connect" link in the sidebar nav. It will now include the `PUBLIC_URL` env var.
=> ui+nav: fix Lightning Node Connect link with custom path

doc/example-nginx.conf
```
Also escape the "." for more precise regex matching
```
Not matching /litrpc.* locations results in lost grpc calls, which looks like this to the user:
=> docs: Match and pass /litrpc.* locations in nginx

app/src/__tests__/components/pool/BatchSection.spec.tsx, app/src/__tests__/components/pool/OrderFormSection.spec.tsx, app/src/__tests__/util/formatters.spec.ts, app/src/components/common/BadgeList.tsx, app/src/store/stores/batchStore.ts, app/src/store/views/batchesView.ts, app/src/store/views/orderFormView.ts, app/src/util/formatters.ts, app/src/util/strings.ts
Closes #296 
This PR updates the labels for the Lease Durations to be more user friendly. Instead of showing `12096`, it now displays `3 months`. The durations also are now sorted numerically ascending.
=> pool: display lease durations as human readable times

app/src/api/loop.ts
This PR increases the maximum miner fee to mimic the behavior of the `loop` CLI [main.go](https://github.com/lightninglabs/loop/blob/master/cmd/loop/main.go#L263). The `MaxMinerFee` value should be set higher in order to reduce the chances of a swap failure when onchain fees increase after the swap is initiated.
Closes #307, closes #303
=> loop: increase maximum miner fee to reduce swap failures

session/server.go, session_rpcserver.go, terminal.go
Ensure that expired sessions are revoked.
- when `resumeSession` is called but session is expired, it is revoked. 
- if the session is not yet expired, a timeout goroutine is used to ensure that it is stoped and revoked after expiry.
- the first commit adds the ability to subscribe to a session being stopped manually so that the above goroutine can exit when it is no longer needed
=> multi: revoke expired sessions

session/server.go
Ensure that the mailbox grpc connection sends a ping every 2 mins to
ensure that the connection remains open.
=> session: add 2 min mailbox ping

go.mod, go.sum
lnc refused to compile for 32 bit systems because we used the `math.MaxUInt32` value (which is bigger than `int` on 32bit systems).
=> mod: bump lnc to version with fixed int overflow

README.md, cmd/litcli/main.go, itest/litd_mode_integrated_test.go, itest/litd_mode_remote_test.go, itest/litd_node.go, rpc_proxy.go, session/macaroon.go, session_rpcserver.go, subserver_permissions.go, terminal.go
Part of https://github.com/lightninglabs/lightning-node-connect/issues/17.
Depends on https://github.com/lightninglabs/lightning-terminal/pull/294 and https://github.com/lightninglabs/lightning-terminal/pull/292, only the last 9 commits are new.
Can be tested locally by baking a super macaroon with:
```
lncli bakemacaroon --save_to /tmp/readonly.supermacaroon --root_key_id 18441921392371826688 --allow_external_permissions offchain:read swap:read insights:read suggestions:read auth:read rates:read order:read peers:read message:read recommendation:read info:read report:read auction:read onchain:read account:read invoices:read terms:read macaroon:read audit:read
```
And then interact with one of the daemons:
```
pool --rpcserver localhost:8443 --tlscertpath ~/.lit/tls.cert --macaroonpath …
```
=> Support super macaroon in remote lnd mode

cmd/litcli/sessions.go
The default expiry of one hour was way too short for anything practical
and we increase it to 90 days which is almost three months.
The user can still override this value manually by specifying the flag.
=> cmd/litcli: change default session expiry to 3 months

go.mod, go.sum, itest/litd_mode_integrated_test.go, log.go, session/server.go, session/store.go, session_rpcserver.go
In this commit, we update the go mod to point to the version of LNC that
contains the logic for handshake version 2. This requires that we pass
in a call back that LNC can call to persist the remote static key once
it is received. This then needs to be provided each time we start up the
session again.
depends on https://github.com/lightninglabs/lightning-node-connect/pull/35
=> multi: persist remote static key for handshakev2

app/src/components/common/FormSelect.tsx, app/src/components/connect/AddSession.tsx, app/src/components/layout/Layout.tsx, app/src/components/theme.tsx, app/src/emotion-theme.d.ts, app/src/i18n/locales/en-US.json, app/src/store/models/session.ts, app/src/store/stores/sessionStore.ts
This PR updates the `AddSession` component, allowing users to generate either admin or read-only macaroons for connecting to their node.
=> Add support for read-only macaroons

Dockerfile
We bumped the NodeJS version which also pulled in a new version of Alpine that no longer knows the `python` package (it's now explicitly called `python3`).
But since we don't require the binary any longer anyway, we remove it.
=> docker: fix build by removing unused python install

README.md, version.go
We forgot to bump the app version, so we bump everything to the next one to avoid confusion. Will create a new release and basically replace 0.6.6 with this one.
=> README+version: bump version to v0.6.7-alpha

app/src/components/pool/account/CloseAccountConfirm.tsx, app/src/components/pool/account/FundAccountConfirm.tsx, app/src/components/pool/account/FundNewAccountConfirm.tsx, app/src/components/pool/account/RenewAccountConfirm.tsx, app/src/store/views/closeAccountView.ts, app/src/store/views/fundAccountView.ts, app/src/store/views/fundNewAccountView.ts, app/src/store/views/renewAccountView.ts
This PR fixes a recurring issue where users were creating multiple Pool accounts via the UI by clicking on the "Create Account" button while the previous request was in-flight. To resolve this, we disable the buttons immediately after being clicked for account modification requests (init, deposit, renew, close).
=> ui+pool: disable buttons during account changes

app/package.json, app/src/config.ts, app/src/store/store.ts
Implements a new script (`yarn develop`) that lets developers to do
LiT frontend client development without having to setup an `lnd` backend.
This script uses the mock responses configured in `sampleData` to resolve API
requests.
Limitations:
* The implementation depends on `sampleData` to be up-to-date as the APIs
evolve.
* Currently it only supports `GET` requests.
Alternatives considered:
* Use `REACT_APP_DEV_HOST` to point to a `testnet` public server so as to avoid
configuring and running `lnd`.
* Set up a webpack devserver to proxy responses to a node server running
locally that in-turn reads mock responses configured as `<endpoint>.json`
files, ex `GetInfo.json`, and sends it as response.
=> Standalone LiT client development

README.md, terminal.go, version.go
Because Loop requires a new version, we also need to bump the overall
minimum required version of lnd in LiT to `v0.14.3-beta`.
=> New release: v0.7.0-alpha

app/src/components/tour/WelcomeStep.tsx
This is a small PR to update the link in the Welcome step of the tour on the Loop page.
=> tour: update documentation link in the welcome step

.github/dependabot.yml
Replaces #400 
This dependabot config option  instructs the bot to not open PR for *version* updates. As mentioned in the [docs](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#overriding-the-default-behavior-with-a-configuration-file), it will only open PRs for *security* updates. They also should only be for production dependencies.
=> chore: exclude dependabot version updates

app/src/components/connect/SessionRow.tsx, app/src/components/theme.tsx, app/src/emotion-theme.d.ts
The day has arrived, PRs for litd! 
Starting small though.
ui+common: adds `lightningRed` theme color
ui+connect: switches pink for new red color + updates bottom border color
Before:
After:
=> ui+connect: minor connect view styling updates

README.md, app/src/types/generated/lit-sessions_pb.d.ts, app/src/types/generated/lit-sessions_pb.js, app/src/util/tests/sampleData.ts, go.mod, go.sum, version.go
Prepare the repo for a new minor release.
=> New release: v0.7.1-alpha

itest/litd_mode_integrated_test.go, itest/litd_mode_remote_test.go, make/release_flags.mk, rpc_proxy.go, session_rpcserver.go, subserver_permissions.go, terminal.go
In this commit, we include all LND's rpc subserver permissions in the permission list used to create the macaroons used in Litd (for sessions etc). The way this is done is a temporary solution while we wait for an LND change that exports the permissions required by each subserver. 
Fixes https://github.com/lightninglabs/lnc-web/issues/60
Run alongside https://github.com/lightninglabs/lightning-node-connect/pull/55 to test
=> subserver_perms: add Lnd's registered subserver perms

config.go, log.go, rpcmiddleware/config.go, rpcmiddleware/interface.go, rpcmiddleware/interface_test.go, rpcmiddleware/log.go, rpcmiddleware/manager.go, rpcmiddleware/proto.go, terminal.go
This PR separates the rpcmiddlware package away from the accounts interceptor logic in https://github.com/lightninglabs/lightning-terminal/pull/363
=> multi: rpcmiddleware package

.github/workflows/main.yml, Makefile
Currently only the unit-race check and the integration tests are run. 
This commit ensures that the unit tests are also run.
=> Makefile+github: run unit tests

README.md
Updates the readme after the recent emergency update was pushed out.
=> README: update version matrix for v0.8.1-alpha

cmd/litcli/sessions.go, itest/litd_mode_integrated_test.go, perms/permissions.go, perms/permissions_test.go, rpc_proxy.go, session_rpcserver.go, terminal.go
With this PR, you can now use the wild card character when specifying custom URIs that permissions should be added for in an LNC session. This allows you to do the following:
```
litcli s a --label=custom_perm_session  --type=custom --uri=/lnrpc.Lightning/ListChannels --uri="/poolrpc.Trader/*"
```
The above will create a session that has the perms to only access the `ListChannels` call of the `lnrpc.Lightning` but then also has the perms to access any URI that falls under the `poolrpc.Trader` service. 
`
Fixes #439
=> multi: support using a regex when specifying custom perms

litrpc/lit-sessions.pb.go, litrpc/lit-sessions.proto, perms/permissions_test.go, session_rpcserver.go
A special case is added to the creation of a custom session to 
allow the user to specify custom URIs as well as the permissions 
for all read-only endpoints. To use this option when creating a 
custom session, a user should set the `entity` of the macaroon 
permission to `"uri"` and the `action` to `"***readonly***"`
The reason for the using the three '*'s in the string is to ensure 
that the string never collides with a valid URI or a valid regex. 
`litcli` example:
```
litcli  s a --label=test --type=custom --uri=/lnrpc.Lightning/ListChannels --uri="/lnrpc.State/.*" --uri="***readonly***"
```
Fixes #456
=> session_rpcserver+litrpc: allow custom session with all read-only perms

.github/actions/setup-go/action.yml, .github/actions/setup-node/action.yml, .github/workflows/main.yml, tools/Dockerfile
Fixes the linter failure that appeared out of nowhere in all our projects: https://github.com/lightninglabs/lightning-terminal/actions/runs/3843975095/jobs/6547862365
=> tools: fix lint VSC permission error

itest/litd_mode_integrated_test.go, litclient/jsoncallbacks.go, perms/permissions.go, terminal.go
This PR does 2 things: 
1. Adds a `litclient` package and adds and exports a list of JSON callbacks that a client connecting to lit should register. 
2. Adds a `withAllSubServers` param to perms.NewManager. This is useful for a client who wants to get a list of all possible permissions available to it without knowing which sub-servers LND was compiled with. This will lead to some false positives if the client tries to call the method of a sub-server that was not compiled within LND.
required for https://github.com/lightninglabs/lightning-node-connect/pull/66
=> multi: add some litd client helpers

make/release_flags.mk
Fixes https://github.com/lightninglabs/lightning-terminal/issues/491.
=> make: add darwin-arm64 to release build architectures

terminal.go
The macarooon db should be under the network directory.
Small oversight made [here](https://github.com/lightninglabs/lightning-terminal/pull/517/files#diff-76dcb3ff0bf98acc001558927365f8a3b7f0d2253580a49dc5973dfa398372c7R678-R687)
=> terminal: fix macaroon DB directory

app/build/.gitkeep, app/package.json
Fixes the `terminal.go:99:13: pattern app/build/*: no matching files found` error when litd is used as a library or module in another project.
Even though the content of the app/build directory should be ignored by
git, we need it to exist in order for the Golang embedded file system
compilation to succeed on an empty project. This is required to fix
compilation issues when lightning-terminal is used as a module
dependency in another project, where the frontend build process can't be
triggered.
=> Fix "no matching files found" compilation error when litd is used as a library

doc/config-lnd-remote.md
Adds a small note in the doc for connecting `litd` to remote `lnd`. It is not clear that the LND `admin.macaroon` and `tls.cert` should not be placed inside the `.lit/` directory, as they may be overwritten.
=> doc: add note for remote lnd credentials

config.go, itest/litd_mode_integrated_test.go, perms/manager.go, rpc_proxy.go, subservers/faraday.go, subservers/interface.go, subservers/loop.go, subservers/manager.go, subservers/pool.go, subservers/subserver.go, terminal.go
This PR is the first couple of commits of https://github.com/lightninglabs/lightning-terminal/pull/537 without the disabling logic.
=> multi: modularise subserver handling 

itest/litd_node.go, itest/network_harness.go, itest/server_harness.go
In this PR we export the itest structs `ServerHarness` and `HarnessNode`. This is useful to make it possible to use the structures independently in other test frameworks that need to run and interact with Lit instance(s), and reuse the structures from the `lightning-terminal` repo.
Let me know if there are other components of the itest framework that you think would be useful to export, and I'll update this PR with those as well :)!
=> itest: export `ServerHarness` and `HarnessNode`

go.mod, go.sum
This PR bumps the `lndclient` version to one that ensures that a more meaningful error
is returned if `RegisterRPCMiddleware` fails. Currently, the wanted error will be logged but
the official error will be `context cancelled` which is not very helpful. 
This will be especially important once https://github.com/lightninglabs/lightning-terminal/pull/541 is merged since we want 
meaningful errors to be displayed.
=> go.mod: bump lndclient to 0.16.0-12

go.mod, go.sum
This is a draft PR in order to be able to easily test the fix for issue #540.
This PR replaces the lndclient dependency with a fork that has the macaroon regeneration fix.
Fixes #540
=> mod: bump `lndclient` to `v0.16.0-13`

Makefile
This PR adds installation of the `litcli` executable when running the `make go-install-cli` command. The command should install all cli executables.
Happy to address any feedback! :)
=> make: install litcli with `make go-install-cli`

config.go
Fix the macaroon path construction so that even if the network is not mainnet, the path gets constructed correctly from a user specified "--lit.dir" flag.
Fixes #596
=> config: fix macaroon path construction

README.md, go.mod, go.sum, version.go
This PR updates litd to `v0.10.4-alpha`.
In this PR, we also bump taproot-assets to the latest release.
Happy to address any feedback :)!
=> Update litd to version `v0.10.4-alpha` 

firewall/privacy_mapper_test.go, firewalldb/privacy_mapper.go, firewalldb/privacy_mapper_test.go, rules/chan_policy_bounds.go, rules/channel_restrictions.go, rules/channel_restrictions_test.go, rules/history_limit.go, rules/interfaces.go, rules/peer_restrictions.go, rules/peer_restrictions_test.go, rules/rate_limit.go, session_rpcserver.go
In this PR, we ensure that if we are linking a session to a previous one, that we extract any existing real-to-pseudo pairs from the privacy map DB instead of generating new ones.
=> rules+session_rpc: use existing privacy mapper for obfuscating rules of linked sessions

accounts/service.go
Fixes https://github.com/lightninglabs/lightning-terminal/issues/638.
It can happen that we see the payment request for a payment coming in, register it, but then it is failed on the lnd level and basically never exists in the DB.
In that case we can just stop tracking the payment.
=> accounts: don't error out on payment not initiated

itest/litd_mode_integrated_test.go, itest/litd_mode_remote_test.go, perms/manager.go, perms/permissions.go, rpc_proxy.go, subservers/faraday.go, subservers/interface.go, subservers/loop.go, subservers/manager.go, subservers/pool.go, subservers/taproot-assets.go, terminal.go
This PR does a few things:
1. Ensures that Lit register's LND's State server to it's REST server 
2. Allow LND's & Lit's and all Lit's subserver's whitelisted endpoints to pass through without requiring a macaroon
=> multi: allow LND and subserver whitelisted calls

terminal.go
In this commit, we ensure that when we wait on the macaroon channel for the macaroon from the integrated LND, that we also listen to other exit signals such as the interceptor, lndQuit chanel and the error channel. This is to prevent shutdown from blocking forever in the case where there was an issue preventing LND from sending the initial macaroon.
The issue was caught in this comment: https://github.com/lightninglabs/lightning-terminal/pull/541#discussion_r1285486027
=> terminal: dont block indefinitely on macaroon channel

accounts/checkers.go, accounts/checkers_test.go, accounts/interceptor.go, accounts/interface.go, accounts/rpcserver.go, accounts/service.go, accounts/service_test.go, config.go, itest/litd_mode_integrated_test.go, itest/litd_mode_remote_test.go, rpc_proxy.go, subservers/subserver.go, terminal.go
This PR is based on #541
In this PR we ensure that if the accounts service critically errors, we won't shutdown LiT, but instead log the error and reject any new requests to the accounts service.
We also add the accounts service to the status manager, and use the status from the status manager to determine if we should allow gRPC requests for the accounts service through or not.
Finally, we also add a config option to allow users to disable the accounts service, which ensures that the accounts service isn't started if the config option is set to `disable`.
TODO:
=> Don't shutdown lit on accounts service critical error, and register to status server

accounts/service.go
This PR fixes a simple check in the `UpdateAccount` RPC handler which checks if the service is running.
=> accounts: fix service check in UpdateAccounts call

cmd/litcli/accounts.go, cmd/litcli/actions.go, cmd/litcli/autopilot.go, cmd/litcli/helpers.go, cmd/litcli/main.go, cmd/litcli/privacy_map.go, cmd/litcli/proxy.go, cmd/litcli/sessions.go, cmd/litcli/status.go
This PR addresses some of the problems with the litcli --help message reported in [Issue 591](https://github.com/lightninglabs/lightning-terminal/issues/591).
These changes affect the text displayed in the help messages and do not affect any functionality of the application. Everything else was left unchanged.
The changes are as follows:
1. The command categories were reorganized.
2. Descriptions were changed to be as consistent as possible in format, punctuation and capitalization. However, there were a few limitations as a result of the way the cli package works (see below). The result is a much more consistent appearance, but not perfectly consistent across all types of descriptions.
3. An attempt was made to make all line spacing consistent where possible.
4. All references to …
=> main: make cmd documentation coherent

autopilotserver/mock/server.go, itest/litd_firewall_test.go
In this PR, we add a session linking itests which aims to test behaviour across linked sessions. Particularly:
1) that calls through linked sessions make use of the same privacy mapper
2) that obfuscated rule values (like channel IDs) use the same privacy mapper across linked sessions
3) that the rule enforcer uses the same DB across linked sessions
=> itests: add session linking test

app/src/util/constants.ts
I spoke with @jamaljsr and we noticed that some of the V2 methods are not currently included when setting custom permissions and the deprecated versions are. This would cause any applications using LNC with the V2 methods to get a permissions error even though the user granted permission for these values. Adding these will now support clients that are using the latest LND API versions.
=> fix: add new v2 methods to custom permissions

.github/workflows/main.yml, accounts/service_test.go, cmd/litcli/accounts.go, cmd/litcli/actions.go, cmd/litcli/autopilot.go, cmd/litcli/helpers.go, cmd/litcli/sessions.go, cmd/litcli/status.go
The linter was disabled before due to a bug. Since the bug was likely
caused by an issue with a go module in a dependency project which was
updated in the meantime, we attempt to re-enable the linter in the CI
now.
=> linter: re-enable the linter

status/manager.go
In #694 we added support for initialising the `subServer` struct with functional options. Unfortunately though, with the last refactors in the PR I forgot to also apply the functional options in `subServer` constructor function. Sorry for that, this was totally my bad! The current resulting behaviour is that the `litcli status` won't function as expected for `lnd`, while `lnd` Subserver is in the `WalletReady` state (until it enters the `Running` state).
This PR addresses the issue, and applies the functional options in the `subServer` constructor.
=> status: apply functional options on subServer init

accounts/service_test.go, accounts/store.go, accounts/store_test.go, cmd/litcli/accounts.go
This PR updates the `accounts` subsystem to allow creation of accounts with an initial balance set to 0.
As accounts can now receive balance through settled invoices during the lifecycle of the account, it makes sense that we'd allow creation of accounts with an initial balance of 0.
=> accounts + main: Allow new accounts with 0 balance

cmd/litcli/autopilot.go
We would like to be able to set different rules for different features. This is solved by introducing JSON-serialized (per-feature) rule flags where all the rules from `litcli autopilot features` can be set.
=> autopilot: generic rules per feature

firewalldb/kvstores.go, firewalldb/kvstores_test.go
In this commit, we fix a bug which would result in the "perm" store being used for the LocalTemp KV DB _if and only if_ the KV store being requested was a session level one (as opposed to a session feature level one). It is ok for us to just change this here since as of this commit, the session level KV store is not used at all and so nothing will be in that store yet.
=> firewalldb: fetch correct bucket for session level temp KV store

accounts/checkers.go, accounts/checkers_test.go, accounts/context.go, accounts/interceptor.go, accounts/interface.go, accounts/log.go, accounts/service.go, accounts/service_test.go, firewalldb/kvstores.go, rpcmiddleware/interface.go
reopening https://github.com/lightninglabs/lightning-terminal/pull/762 
along with a commit that addresses the last review comment made in https://github.com/lightninglabs/lightning-terminal/pull/763
=> accounts: address pendingPayments issues & add tracer

Makefile
This PR modifies the `build-itest` make command such that it builds `litd-itest`. It also adds a new `clean-itest` command which deletes itest binaries.
=> Modify itest make commands

go.mod, go.sum, itest/litd_custom_channels_test.go
To make sure asset channels also function properly with BTC-only
payments, we add a keysend and invoice payment to the integration tests.
=> itest: add BTC-only keysend and invoice payments

config.go, docs/release-notes/release-notes-0.13.1.md
fixes #773 
This PR adds the `tlsextraip` and `tlsextradomain` config fields to the LiT config. This allows users to specify additional IPs and domains to be included in a newly generated LiT TLS certificate. Note that this specifically affects the `litd` tls.cert, and not the `lnd` tls.cert, which is targeted with `lnd.tlsextraip=` & `lnd.tlsextradomain=`.
=> terminal: add `tlsextraip` & `tlsextradomain` to conf

go.mod, go.sum, itest/litd_custom_channels_test.go, itest/litd_node.go, itest/litd_test_list_on_test.go, itest/network_harness.go
In this commit, we add a breach itest for the custom channels. The scenario is as follows:
* Two nodes: Charlie and Dave. 
* Charlie does asset keysends to Dave. 
* Dave snapshots his database. 
* Charlie sends another keysend. 
* Dave breaches. 
* Charlie sweeps both asset UTXOs into a new anchor output after the breach confirms.
=> itest: add breach itest for custom channels

README.md, docs/release-notes/release-notes-0.13.1.md, go.mod, go.sum, version.go
This PR bumps the litd version to `v0.13.1-alpha`.
This PR also bumps lnd to version `v0.18.1-beta`.
@ellemouton, would you please specifically check if this is how we would like to handle the release notes during a release?
=> Bump litd to version `v0.13.1-alpha`

itest/assets_test.go
Since lightninglabs/taproot-assets#987 was merged, this TODO and if statement is no longer needed to make the test pass.
=> itest: remove TODO after fix

version.go
As discussed offline, we'll want to use the `.99` version suffix for the Taproot Asset Channel functionality, since this is on a staging branch and we don't know what actual/final version this is going to land in.
To make sure we don't conflict with other release version numbers of `litd` on the `master` branch (such as the upcoming https://github.com/lightninglabs/lightning-terminal/pull/752 or a version that'll include [`lnd v0.18.2-beta`](https://github.com/lightningnetwork/lnd/pull/8901)) we use a non-conflicting minor version for now.
=> version: bump to v0.13.99-alpha.rc2

README.md
Fixes a couple of dead links due to the `doc` folder having been renamed to `docs`.
=> multi: fix broken links to renamed doc folder

README.md
https://github.com/lightninglabs/lightning-terminal/pull/792/commits/993e1852cedf1d01a29be1e528f682e6096d223c#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R35
eluded 792 review
Comprehensiveness confirmed by grepping
`\(\./doc/`
=> multi: fix broken link to renamed docs folder

README.md, cmd/litcli/ln.go, go.mod, go.sum, itest/assets_test.go, itest/litd_custom_channels_test.go, itest/litd_node.go, itest/litd_test_list_on_test.go, subservers/taproot-assets.go, terminal.go, version.go
Reported offline by @jamaljsr.
Depends on https://github.com/lightningnetwork/lnd/pull/8908.
Depends on https://github.com/lightninglabs/taproot-assets/pull/1011.
Fixes a bug that when an invoice is paid, the full invoice amount is checked when validating the local channel balance and reserve. But for custom channels the actual HTLC amount might be just above dust and shouldn't validate the channel reserve.
We update our itest to reproduce the issue and then update to the lnd commit that fixes it.
=> mod+itest: reproduce and fix reverse direction invoice payment, bump to rc4

go.mod, go.sum, itest/litd_custom_channels_test.go
Depends on https://github.com/lightninglabs/taproot-assets/pull/1021.
This commit adds a test case for the edge case that previously lead to a panic in the sender of an HTLC if the initiator of a channel didn't have any asset balance in the channel anymore.
=> mod+itest: add test case for initiator having zero balance

config.go, go.mod, go.sum, itest/assets_test.go, itest/litd_custom_channels_test.go
Adds another test case where we co-op close an asset channel when the full balance is on the non-initiator/recipient's side of a channel and assert the final balances are distributed correctly.
This also fixes https://github.com/lightninglabs/taproot-assets/issues/1019, by addressing the last of the 3 reported issues (pending channel staying forever).
=> custom channels: add more itest coverage, fix pending channel bug

version.go
As discussed offline, we're going with the `-experimental` version suffix for the Taproot Asset Channel release to signify it's non-production-readiness. The version suffix will also show in release binary artifacts and docker images tags.
=> version: change "alpha" to "experimental" for Taproot Asset Channel release

docs/release-notes/release-notes-0.13.4.md, terminal.go
Fixes https://github.com/lightninglabs/lightning-terminal/issues/805.
When lnd isn't marked as fully ready yet, we didn't allow any REST methods through. But to allow creating a wallet through REST, we also need to allow these methods.
=> terminal: allow wallet unlocker services REST calls

accounts/checkers_test.go, accounts/service_test.go, cmd/litcli/ln.go, go.mod, go.sum, itest/assets_test.go, itest/litd_accounts_test.go, itest/litd_custom_channels_test.go
Depends on https://github.com/lightninglabs/taproot-assets/pull/1048.
~Depends on https://github.com/lightningnetwork/lnd/pull/8947.~
Uses the new `tapchannelrpc` RPC methods `SendPayment` and `AddInvoice` that do the RFQ part inline, so we don't have to keep that logic in the `litcli` code.
=> [custom channels]: Use new `tapchannelrpc` RPC methods

litclient/jsoncallbacks.go
Add the `priceoraclerpc`, `rfqrpc`, and the `tapchannelrpc` JSON callbacks to the litclient's `Registrations` array. This allows the litclient to use the rpc functions contained in these JSON callbacks.
These registrations are required for apps using the LNC (wasm) to call RPC methods. Without these additional callbacks, the wasm will return a "RPC method not found" error when calling RPCs contained in these packages.
=> litclient: add taprpc packages to `Registrations`

.github/workflows/docker.yml
Added a daily schedule to the Docker workflow to automate builds and
pushes of the `daily-testing` image. This change introduces a new cron
job that runs every day at midnight (UTC) and triggers the workflow.
Additionally, updated the workflow to set different environment
variables for daily builds, including `RELEASE_VERSION` and `IMAGE_TAG`.
These changes enable the automatic creation of daily testing images with
unique tags.
Inspired by:
https://github.com/lightningnetwork/lnd/blob/57a5e4912bced63ce13be06896f64d7e476616b4/.github/workflows/docker.yml#L7-L44
=> Add nightly schedule to Docker CD workflow

Makefile, app.go, app_noui.go, docs/release-notes/release-notes-0.13.4.md, terminal.go
This commit adds support for building without UI. If the build tag "no_ui" is set the UI will be disabled and an empty `embed.FS` will be served. I'm successfully running it on my nix-bitcoin node with the following nix-bitcoin pkgs/modules https://github.com/sputn1ck/nix-bitcoin/commit/d69e557740b6f4d33a9f48816ee58275c0dbc6a5
NOTE: this doesn't remove the need for an `uipassword`
=> multi: add support for building without UI

.github/workflows/docker.yml
To fix the issue that currently prevents the second image (with the /lit path prefix) to be built and pushed (both for releases and nightly builds), we clear the build cache between builds.
Example failure: https://github.com/lightninglabs/lightning-terminal/actions/runs/10462945206
```
System.IO.IOException: No space left on device : '/home/runner/runners/2.319.1/_diag/Worker_20240820-001701-utc.log'
```
=> .github: clear build cache between image builds

go.mod, go.sum, itest/litd_custom_channels_test.go
Depends on https://github.com/lightninglabs/taproot-assets/pull/1103.
Demonstrates the issue in https://github.com/lightninglabs/taproot-assets/issues/1099, and that the fix works.
=> itest: spend assets after sweeping from force close

config.go, docs/release-notes/release-notes-0.13.4.md, version.go
With this commit, a user can now run `litd --version` instead of needing
to run `litd --lnd.version` or `litcli --version` to obtain the LiTd
version.
Fixes https://github.com/lightninglabs/lightning-terminal/issues/828
=> config: add a "--version" config option 

cmd/litcli/ln.go
Follow up to https://github.com/lightninglabs/lightning-terminal/pull/817 , partial fix for https://github.com/lightninglabs/taproot-assets/issues/1111 .
=> [custom channels]: plumb payinvoice CLI arg

status/manager.go
=> status: fix typos

cmd/litcli/ln.go, docs/release-notes/release-notes-0.13.995.md
Fixes https://github.com/lightninglabs/taproot-assets/issues/1142
The RPC calls were updated to allow composite UTXOs (assets from multiple asset utxos) for funding capability, but the same functionality is not available in the CLI due to the existing sanity check.
This commits changes the sanity check to allow for composite UTXOs by validating whether the running sum of the assets in the UTXOs is greater than the amount to be funded.
=> litcli: relax fundchannel checks

make/release_flags.mk
Fixes https://github.com/lightninglabs/lightning-terminal/issues/863 https://github.com/lightninglabs/lightning-terminal/issues/854
Additional flags produce:
* Globally consistent commitment hash length, regardless of gitconfig
* `--broken` to create fail-safe tag indicating a dirty or corrupted
work tree
* `--always` to generate a tag, even if no tags are reachable from the
current commit.
=> make: update VERSION_TAG to a globally-consistent build-input identifier

itest/assets_test.go, itest/litd_custom_channels_test.go
This PR adds a few more edge cases in the custom channel liquidity edge cases itest.
These extra cases cover scenarios of big payments going through an asset channel, where the asset amount expressed in btc exceeds the btc channel capacity.
=> itest: Extend liquidity edge cases for custom channels 

docs/release-notes/release-notes-0.13.4.md, go.mod, go.sum, itest/assets_test.go, itest/litd_custom_channels_test.go, itest/litd_test_list_on_test.go
We want proper asset balance reporting between lnd and tapd, without asset balances turing up in both the asset balance from tapd and the custom channel balance from lnd.
Currently this behavior is not aligned with that requirement. tapd has currently now way of not reporting asset balances that are actually part of the funding transaction of a custom channel. This is fixed with [taproot-assets PR 1151](https://github.com/lightninglabs/taproot-assets/pull/1151) 
The current PR under review here is dependent on the taproot-assets commit:
https://github.com/lightninglabs/taproot-assets/commit/31d333cce24bf1c20a43b6b3343fd4914713e8c3
Bumping the tap version was included in this commit 5bbf3d7424bcfaffaea3c01c6b47eb4f6fa791f1 and that commit should probably be edited once 1151 is merged.
=> itest: add test for consistent balance reporting

docs/release-notes/release-notes-0.13.5.md, status/manager.go, subservers/manager.go, terminal.go
1) For the subserver manager: use a map instead of an array for subservers. Check that there is no name collision before adding a new server. This is also nice if we want to get a specific subserver by its name (as is done in https://github.com/lightninglabs/lightning-terminal/pull/848). 
2) for the status manager, first check that we are not overriding an existing subserver before we register a new one
=> subserver+status: check map entries before adding new servers

itest/litd_custom_channels_test.go, itest/litd_test_list_on_test.go
The itest `testCustomChannelsMultiInput` verifies multi-input channel funding.
In this test Charlie mints an asset, transfers it to Dave in two
separate txs. Dave then uses both asset UTXOs to fund a channel with
Charlie that is bigger than the value of either UTXO.
=> Add itest for multi input asset funding

README.md, docs/release-notes/release-notes-0.13.6.md, version.go
This PR bumps the litd version to `v0.13.6-alpha`.
This is a hotfix release, which bumps the application version in `litd` to `v0.13.6-alpha`, as I forgot to update the application version in the previous release. Apologies for that! Not modifying the application version for the previous release, resulted in `litd` outputting an incorrect `version`.
For reviewers: I've kept the headings and subheadings in the release notes, despite the body of those sections being empty, following the approach used in lnd. Let me know if you'd prefer a different format for litd. :)
=> Bump `litd` version to `v0.13.6-alpha`

itest/assets_test.go, itest/litd_custom_channels_test.go, itest/litd_test.go, itest/litd_test_list_on_test.go, itest/log.go, itest/oracle_test.go
Depends on https://github.com/lightninglabs/lightning-terminal/pull/848.
This commit adds a fully configurable RPC oracle that can serve asset rates that differ for buy and sell.
We then add a test that shows and asserts proper asset conversion to satoshis and back.
=> itest: add RPC oracle with spread based asset rates

itest/assets_test.go, itest/litd_custom_channels_test.go
Depends on https://github.com/lightninglabs/lightning-terminal/pull/848.
With this commit we sporadically assert in our itests that the outgoing HTLCs for a payment and the incoming HTLCs of an invoice show the custom channel data JSON with the actual asset amounts.
Fixes https://github.com/lightninglabs/lightning-terminal/issues/860.
<details>
<summary>Example invoice</summary>
```
assets_test.go:862: Asset invoice: {
"memo":  "this is an asset invoice over 100000 units",
"r_preimage":  "0b47e516136f867eb8f578ec44e240d4935643050ad47583b14a6c26ffbb20e2",
"r_hash":  "cb502385800559c07812597ee863556fca2c981451668c57a582ad998ebd034d",
"value":  "1718035",
"value_msat":  "1718035941",
"settled":  true,
"creation_date":  "1729615613",
"settle_date":  "1729615613",
"payment_request": …
```
=> [custom channels]: in itest assert payment and invoice HTLCs show custom data

cmd/litcli/ln.go, docs/release-notes/release-notes-0.13.7.md, go.mod, go.sum, itest/litd_custom_channels_test.go, itest/litd_test_list_on_test.go
This commit adds an integration test for the MinRelayFee check. The test ensures that transactions with fees below the minimum relay fee are rejected.
This PR depends on https://github.com/lightninglabs/taproot-assets/pull/1163 which in turn depends on  https://github.com/lightninglabs/lndclient/pull/200
It uses pseudoversions in `go.mod` for ~both~ `taproot-assets` ~and `lndclient`~ that should be updated before merging.
=> Add itest for MinRelayFee check in tapd

.github/workflows/main.yml, Makefile, accounts/checkers_test.go, accounts/service_test.go, perms/mock_dev.go
This PR pull out some commits from https://github.com/lightninglabs/lightning-terminal/pull/848 that don't have any dependency on `lnd v0.18.4` and can be merged immediately.
Didn't add release notes as the improvements are mostly build/development related and don't include any end user features.
=> Build improvements

config.go, docs/release-notes/release-notes-0.13.7.md
The GRPC connection logger is very verbose and normally not very useful. So it leads to more confusion and unnecessary log bloat than it actually helps to debug things.
So we disable it by default, meaning that if GRPC=<level> doesn't appear in the log level config string, we add GRPC=off.
That means we can still manually turn it on by adding ,GRPC=info to the log config (e.g. --lnd.debuglevel=debug,GRPC=info).
See https://github.com/lightninglabs/lightning-terminal/issues/895 for an example where the log is less than useful.
=> config: disable internal GRPC logger by default

.vscode/settings.json
The boolean values for `source.fixAll.eslint` are deprecated. This
commit changes the boolean values to the correct string values.
See: https://code.visualstudio.com/updates/v1_83#_editor
=> Replace deprecated boolean in .vscode with string value

config.go, docs/release-notes/release-notes-0.13.7.md, itest/litd_node.go
=> config: add signet network option

go.mod, go.sum, itest/litd_custom_channels_test.go
Updates the force close HTLC sweep integration test to also do MPP payments, to make sure duplicate script keys due to identical MPP shard HTLCs don't cause an issue.
=> [custom channels]: Assert fix for duplicate script key issues in MPP payments

go.mod, go.sum, itest/assets_test.go, itest/litd_custom_channels_test.go
~Depends on https://github.com/lightninglabs/taproot-assets/pull/1245.~
Asserts the decimal display value for all pending and opened channels.
=> mod+itest: bump tapd, assert asset decimal display

go.mod, go.sum, itest/assets_test.go, itest/litd_custom_channels_test.go, itest/litd_test_list_on_test.go, terminal.go
~Depends on https://github.com/lightningnetwork/lnd/pull/9333.~
Depends on https://github.com/lightninglabs/taproot-assets/pull/1236.
Makes sure channels aren't force closed in certain edge cases.
=> [custom channels]: test forward traffic shaper

dev.Dockerfile
dev.Dockerfile: allow forcing a specific taproot-assets version through a build argument.
An example of usage can be found here: https://github.com/lightninglabs/tapdvalidation/blob/cb7c752e9b123dc99882a471afa04cc1066e5111/docker-compose.yaml#L66
=> dev.Dockerfile: allow forcing a specific taproot-assets version

app/src/__tests__/util/appStorage.spec.ts, app/src/__tests__/util/log.spec.ts, app/src/store/views/appView.ts, autopilotserver/client.go
This pull request corrects several typos in the following files:
- **appStorage.spec.ts**: Changed "an value" to "a value" to fix an article usage error.
- **log.spec.ts**: Corrected "a error log message" to "an error log message" for proper article usage.
- **appView.ts**: Fixed "adds a alert" to "adds an alert" to ensure correct article usage.
- **client.go**: Corrected "returns a autopilot-server client" to "returns an autopilot-server client" to fix article usage.
These changes improve the consistency and accuracy of the code.
=> multi: fix typos

.github/workflows/main.yml, Makefile, docs/release-notes/release-notes-0.14.1.md, make/compile_flags.mk, make/release_flags.mk, make/testing_flags.mk
Some helpers (lots of influence from the `taproot-assets` repo) to give devs more control over running unit tests. 
With this, we can now do things like:
```
make unit pkg=accounts
make unit pkg=accounts case=TestAccountService
make unit tags=test_db_postgres
```
=> makefile: add unit test helpers

.github/workflows/main.yml
the `actions/upload-artifact@v3` is (or it seems might already be) [deprecated](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/). 
As per the [migration notes](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md), the only thing to be aware of is that we need to take care to namespace artifacts correctly so that jobs in the same CI run dont overwrite the artifacts of other jobs with the same name. Luckily in Lit, we only have 1 possible artifact at the moment so no worries re namespacing at the moment. When we start adding different DB backends, then this will come into play
=> .github: bump upload-artifact action to v4

session/privacy_flags.go
This is a [new function](https://pkg.go.dev/slices@go1.21.0#Contains) added in the go1.21 standard library, which can make the code more concise and easy to read.
=> refactor: using slices.Contains to simplify the code

accounts/interface.go, accounts/rpcserver.go, accounts/service.go, accounts/store_kvdb.go, accounts/store_test.go
To prepare the `accounts.Store` to be more SQL compatible, we will want to replace the current
`UpdateAccount` method. Today it takes a full `OffChainAccount` struct, serialises it and replaces
any existing in the DB. This method is not very SQL appropriate as the better pattern is to instead
have specific update methods that read: "Update field X and account with ID Y". 
So this PR starts this process of adding more SQL friendly methods to the interface and thereby 
phasing out the use of `UpdateAccount`. By doing so, we also move very kvdb specific logic out
of the `accounts.InterceptorService`. 
I'm splitting this up over about 3 or 4 PRs since some of the replacements are more complicated than 
others. 
This PR focuses on just replacing the simple ones:
- …
=> [sql-2] accounts: start replacing calls to UpdateAccount

accounts/errors.go, accounts/interface.go, accounts/service.go, accounts/service_test.go, accounts/store_kvdb.go, accounts/store_test.go
(similar PR description to #938 but they are not dependent on each other)
To prepare the `accounts.Store` to be more SQL compatible, we will want to replace the current
`UpdateAccount` method. Today it takes a full `OffChainAccount` struct, serialises it and replaces
any existing in the DB. This method is not very SQL appropriate as the better pattern is to instead
have specific update methods that read: "Update field X and account with ID Y".
So this PR starts this process of adding more SQL friendly methods to the interface and thereby
phasing out the use of `UpdateAccount`. By doing so, we also move very kvdb specific logic out
of the `accounts.InterceptorService`.
I'm splitting this up over about 3 or 4 PRs since some of the replacements are more complicated than
others.
This PR …
=> [sql-3] accounts: replace calls to UpdateAccount

accounts/checkers_test.go, accounts/service_test.go, accounts/store_kvdb.go, accounts/store_test.go, accounts/test_kvdb.go, go.mod, terminal.go
In this commit, we use the clock.Clock type instead of directly calling time.Now().
This is in preparation for cleaner testing against different SQL backends later on in the series.
=> [sql-5] accounts: use clock.Clock

accounts/interface.go, accounts/service.go, accounts/service_test.go, accounts/store_kvdb.go, accounts/store_test.go
With this PR, we complete the `Prepare the accounts Store interface to be ready for a SQL impl` & `Prep unit tests to be ready to pass against a different backend` steps in #917 .
We do 2 things here:
1) we [revert one of the changes](https://github.com/lightninglabs/lightning-terminal/pull/938#discussion_r1918123976) from a previous PR where we change the balance type of `UpdateAccountBalanceAndExpiry` from an int64 to a more strict lnwire.Millisatoshi type. We revert that here though so that we can use the `UpdateAccountBalanceAndExpiry` in a unit test that uses `UpdateAccount` to set the balance to a negative value (which currently _is_ allowed). 
2) The rest of the PR removes the last couple of usages of `UpdateAccount` from tests.
=> [sql-4] accounts: remove last usages of `UpdateAccount`

app/src/api/loop.ts, app/src/store/views/buildSwapView.ts, docs/release-notes/release-notes-0.14.1.md
Fixes #904
Was able to reproduce this bug on regtest by changing the fee rate on one of my test nodes.
Fix was pretty simple because the `swapView` and loop protobuf definitons already had all of the necessary variables and functions defined :tada:
=> Add lastHop parameter for loop in quotes

.github/workflows/docker.yml
Fixes https://github.com/lightninglabs/lightning-terminal/issues/818.
With the experimental branch now merged into master, we can remove the TODO and actually build the nightly images from master.
=> GitHub: build nightly docker image from master

accounts/rpcserver.go, cmd/litcli/helpers.go, itest/litd_firewall_test.go, macaroons/macaroons.go, macaroons/super_mac.go, macaroons/super_mac_test.go, rpc_proxy.go, session/interface.go, session/macaroon.go, session_rpcserver.go, terminal.go
A pure refactor/code-move PR to move any helper functions and types from the `sessions`
package to the new `macaroons` package. This is to help avoid import cycles later on when 
the session package starts to import from the accounts package (for when a session links to an
account) which also makes use of these macaroon helpers/types.
Part of https://github.com/lightninglabs/lightning-terminal/issues/966
=> [sql-10] sessions: decouple super macaroon helpers from `sessions` package

session/interface.go, session/kvdb_store.go, session/store_test.go, session_rpcserver.go
In this PR, we make various changes to the ListSessions method of the Store interface such that it
can better be implemented by a SQL backend. See commit messages for more details.
Part of #966
=> [sql-12] sessions: make ListSession methods SQL ready

itest/litd_firewall_test.go
This fixes a flake that has been occurring in our itests more and more frequently where we try
to open a second channel with one of our channel peers immediately after a restart. But we might
not yet have connected with them. So we should wait for the reconnect before we attempt to open 
the channel.
=> itest: ensure peer is connected before channel open

.golangci.yml, autopilotserver/client.go, config.go, firewall/config.go, firewall/privacy_mapper_test.go, rpcmiddleware/config.go, subservers/config.go
Activate the line-length-too-long linter
=> golangci: enable line length linter

accounts/interface.go, accounts/service.go, accounts/store_kvdb.go, accounts/store_test.go
Part of https://github.com/lightninglabs/lightning-terminal/issues/648
This PR adds DB preparation required for the KVDB store, in order to support functionality which allows crediting or debiting an account's balance by a given amount.
=> accounts: Credit and debit accounts `kvdb` additions prep

.github/workflows/main.yml, accounts/interface.go, accounts/store_sql.go, accounts/store_test.go, accounts/test_kvdb.go, accounts/test_postgres.go, accounts/test_sqlite.go, make/testing_flags.mk
Part of #917 
In this commit, we add the SQLStore type which implements the
accounts.Store interface. To demonstrate that it works as expected, we
also plug this implementation into all the account unit tests to show
that they pass against the sqlite and postgres backends.
One can use `make unit pkg=accounts tags=test_db_postgres` or
`make unit pkg=accounts tags=test_db_sqlite` to test locally.
=> [sql-7] accounts: add SQL implementation of the accounts store

.github/workflows/main.yml, .golangci.yml, config.go, config_dev.go, config_prod.go, itest/litd_node.go, make/testing_flags.mk, terminal.go
This completes the final step of the accounts section in phase 1 of https://github.com/lightninglabs/lightning-terminal/issues/917
Here we run our CI itests against all DB types. As of this PR, that means that the accounts store is spun up with different DB backends for the various iterations. 
(more detailed description to follow)
=> [sql-8]: run itests against all DB types

session/interface.go, session/kvdb_store.go, session/store_test.go, session_rpcserver.go
See https://github.com/lightninglabs/lightning-terminal/issues/979 for more context. 
In this PR, we do the refactor to make session creation happen in 1 atomic DB transaction as described in the issue above. 
Fixes https://github.com/lightninglabs/lightning-terminal/issues/979
=> [sql-14] sessions: atomic session creation

session/interface.go, session/kvdb_store.go, session/store_test.go, session/tlv_test.go, session_rpcserver.go
For a cleaner interface, adjust the NewSession method of the Session
store such that all optional arguments are functional options.
We also now will error out in `AddAutopilotSession` if the caller specifies privacy map flags without actually
activating the privacy mapper.
=> [sql-15] sessions:  various functional options for NewSession

itest/litd_firewall_test.go, session/errors.go, session/kvdb_store.go, session/store_test.go, session/test_kvdb.go
In preparation for having the unit tests pass against a different Store
implementation, we standardise some of the errors that get returned.
In preparation for adding helpers with the same names but that will
compile under different build flags, we add the helper DB constructors
to use when testing the session store logic against a KVDB backend.
Part of #917
=> [sql-17] sessions: test preparation 

firewall/privacy_mapper.go, firewall/rule_enforcer.go, firewalldb/actions.go, firewalldb/actions_test.go, firewalldb/interface.go, firewalldb/mock.go, session/interface.go, session/kvdb_store.go, session/server.go, session/store_test.go, session_rpcserver.go
In preparation for adding a SQL implementation of the Store interface, which will make calls that require a context, we update the store interface such that all methods take a context. 
Many commits but all just passing context through. So review load is small.
=> [sql-16] sessions: update Store interface methods to take a context

accounts/store_sql.go, session/interface.go, session/kvdb_store.go, session/store_test.go, session_rpcserver.go
This is the last PR for preparing the sessions Store to be ready for a SQL implementation. 
3 unrelated tiny commits - see commit messages for details :)
=> [sql-19] sessions: last misc prep commits

firewall/privacy_mapper.go, firewall/rule_enforcer.go, firewalldb/interface.go, firewalldb/mock.go, session/interface.go, session/kvdb_store.go, session/server.go, session/store_test.go, session_rpcserver.go
Ok actual actual last moulding PR before plugging in the SQL backend :) 
See commit messages for more details.
=> [sql-20] sessions: more re-shaping

db/sqlc/migrations/000001_accounts.down.sql, db/sqlc/migrations/000001_accounts.up.sql
Replace any named UNIQUE indices in the accounts tables and replace with named ones. This is for a future where we want to be able to edit these indices without having to drop the table.
It is fine for us to just edit these tables since these are not available in "prod" yet.
=> [sql-23] db/sqlc: only use named UNIQUE indices

firewalldb/interface.go, firewalldb/kvstores.go, firewalldb/kvstores_test.go, rules/mock.go, rules/onchain_budget.go
This PR does 1 main things:
1) updates various of the rule db kv-store interfaces to take contexts and then threads contexts through where necessary. 
2) creates a generic `DBExecutor` interface and use init the KVStores interface. Later on we will use it to replace the PrivacyMap interface too.
part of https://github.com/lightninglabs/lightning-terminal/issues/917
=> [sql-23] firewalldb: thread contexts through for kv-store interfaces

cmd/litcli/main.go, docs/release-notes/release-notes-0.14.2.md
Adds ability to global flags to de config using ENV variables.
This is useful when running `litcli` in containers.
More context at this very same change applied over `lncli` -> lightningnetwork/lnd#7693
=> litcli: Global flags to accept ENV vars overrides.

config_dev.go, config_prod.go, session/sql_store.go, session/test_kvdb.go, session/test_postgres.go, session/test_sql.go, session/test_sqlite.go, terminal.go
In this PR, the SQL implementation of the `sessions.Store` is added. 
part of https://github.com/lightninglabs/lightning-terminal/issues/917
=> [sql-22] session: sessions CRUD

itest/assets_test.go
small elimination of unnecessary redundant code
=> re-use `createNormalInvoice` in `createAndPayNormalInvoiceWithBtc`

.github/workflows/main.yml
Our failed logs have not been uploading since [this](https://github.com/lightninglabs/lightning-terminal/pull/1006/commits/6dbb68b4e52c0379fe5915b947cf0081292c5890) commit in which we started to namespace itest CI artefacts. I forgot to add the namespace tag to the zip directory.
=> .github: correctly name log zip file to be namespaced

firewall/privacy_mapper.go, firewall/privacy_mapper_test.go, firewall/rule_enforcer.go, firewalldb/kvdb_store.go, firewalldb/kvstores.go, firewalldb/privacy_mapper.go, firewalldb/privacy_mapper_test.go, rules/chan_policy_bounds.go, rules/channel_constraints.go, rules/channel_restrictions.go, rules/channel_restrictions_test.go, rules/history_limit.go, rules/interfaces.go, rules/onchain_budget.go, rules/peer_restrictions.go, rules/peer_restrictions_test.go, rules/rate_limit.go, session_rpcserver.go
Here we do a a few things:
1) thread contexts through for privacy mapper interfaces
2) use the new DBExecutor to init the PrivacyMapDB
3) Unify the kv store and privacy map implementations of DBExecutor to a single bbolt backed one. Later on we will add a sql backed one
=> [sql-24] firewalldb: thread contexts through for privacy mapper interfaces

go.mod, go.sum, itest/assets_test.go, itest/litd_custom_channels_test.go, itest/litd_test_list_on_test.go
~Depends on https://github.com/lightningnetwork/lnd/pull/9504.~
~Depends on https://github.com/lightninglabs/taproot-assets/pull/1441.~
Serves as validation code for the changes in https://github.com/lightningnetwork/lnd/pull/9504.
Also fixes https://github.com/lightninglabs/lightning-terminal/issues/940.
=> multi: bump to latest lnd/tapd, assert close chan data

make/compile_flags.mk
This commit adds support for all other databases
as they are supported in the standalone lnd
builds.
=> build: add build flags for other databases

docs/release-notes/release-notes-0.14.2.md, itest/litd_mode_integrated_test.go, terminal.go
Fixes issue #1027 
Previously, the `Proxy` service was not accessible over LNC, as we did not want to expose the `stop` and `bakesupermacaroon` endpoints over LNC. This also meant that the `getinfo` endpoint was not accessible over LNC. As we now have demand to expose the `getinfo` endpoint over LNC, we have decided to expose the `Proxy` service over LNC, and let the user fine-tune the access to the `stop` and `bakesupermacaroon` endpoints via the macaroon for the LNC session instead.
=> multi: expose `Proxy` service over LNC

config_dev.go, firewalldb/kvstores_sql.go, firewalldb/sql_store.go, firewalldb/test_kvdb.go, firewalldb/test_postgres.go, firewalldb/test_sql.go, firewalldb/test_sqlite.go, session/sql_store.go
This PR adds the SQL version of the RulesDb
=> [sql-29]: firewalldb: implement SQL version of RulesDB (kvstores)

go.mod, go.sum, itest/assets_test.go, itest/litd_custom_channels_test.go, itest/litd_test_list_on_test.go
We sprinkle around some group keys across the grouped asset custom channels test. Some of the invoices and payments in that test now use a group key instead of a specific asset ID.
Related tapd PR: https://github.com/lightninglabs/taproot-assets/pull/1423/commits
For the liquidity edge cases itest, we now support running it in assetID & groupKey mode, meaning we can go through the full suite of edge cases by using either a single assetID or a groupKey.
=> Custom channels itest: Use group keys on some payments & invoices

go.mod, go.sum, itest/assets_test.go, itest/litd_custom_channels_test.go
Updates the balance checks to account for the changes in https://github.com/lightninglabs/taproot-assets/pull/1198.
=> itest: update balance assertions after changes to script key type handling

itest/assets_test.go, itest/litd_accounts_test.go, itest/litd_custom_channels_test.go
This new custom channels liquidity edge case tests that an asset HTLC with more units than the local balance may not get added to the channel.
Based on 
https://github.com/lightninglabs/taproot-assets/pull/1462
https://github.com/lightningnetwork/lnd/pull/9687
=> Add new custom channels itest liquidity edge case for safe HTLC failure

.github/workflows/main.yml, go.mod, go.sum, itest/litd_test_list_on_test.go
Runs the litd/terminal only itests separately from the custom channel itests, so flakes can be seen more clearly and ignored if not relevant.
=> mod+itest: make custom channel itest flakes less annoying

itest/assets_test.go, itest/litd_custom_channels_test.go
This itest tests the behavior exposed in https://github.com/lightninglabs/taproot-assets/pull/1448
It is very minimal, and currently only to be used as a proof-of-concept sanity check for the above feature.
=> Asset Invoice with sats value itest

go.mod, go.sum, itest/assets_test.go, itest/litd_custom_channels_test.go
Depends on https://github.com/lightninglabs/taproot-assets/pull/1505.
Depends on https://github.com/lightninglabs/lightning-terminal/pull/1054.
=> custom channels: add coop close balance assertions for grouped asset channels

itest/assets_test.go, itest/litd_custom_channels_test.go, itest/litd_test_list_on_test.go
Adds an integration test that does a circular self-payment to swap BTC to assets, using a one-hop payment through the RFQ peer.
=> itest: add circular btc-to-asset re-balance test

firewalldb/action_paginator.go, firewalldb/actions.go, firewalldb/actions_kvdb.go, firewalldb/actions_test.go, session/interface.go, session_rpcserver.go
Here we move the filter logic behind the method so that our sql implementation of ListActions can make use of indexes later on instead of how it is done in the bbolt  where the filters are applied in memory. 
This is quite a big diff in a single commit - so I'm just dedicating this PR to the single commit to help with review load.
=> [sql-35]: firewalldb+rpcserver: refactor ListActions

Makefile, dev.Dockerfile
We now run `make go-install-noui` and `make go-install-cli-noui` when
the `NO_UI` build arg is set to 1 to skip building of the web UI when
using the development docker container. If the `NO_UI` build arg is not
set, `make go-install` and `make go-install-cli` are run as before the
`NO_UI` build arg existed.
The Makefile also had to be slightly modified to support this feature.
This feature allows quicker rebuilding when using docker if you aren't doing anything with the web UI.
=> dev.Dockerfile: allow skipping build of the web UI 

firewall/request_logger.go, firewall/rule_enforcer.go, firewalldb/actions.go, firewalldb/actions_kvdb.go, firewalldb/actions_test.go, firewalldb/interface.go, session_rpcserver.go, terminal.go
Here, we add an abstract `ActionsDB` interface that we will later add a SQL implementation for. 
Part of #917
=> [sql-36] actions: prepare ActionsDB interface

cmd/litcli/ln.go, docs/release-notes/release-notes-0.14.2.md, go.mod, go.sum, itest/assets_test.go, itest/litd_custom_channels_test.go, itest/litd_test_list_on_test.go
Depends on https://github.com/lightninglabs/taproot-assets/pull/1498.
Fixes https://github.com/lightninglabs/taproot-assets/issues/1497.
Fixes https://github.com/lightninglabs/taproot-assets/issues/1183.
@ZZiigguurraatt can you help test this PR please?
=> cli: add group key support to channel related calls.

firewall/privacy_mapper.go, firewall/privacy_mapper_test.go, firewall/request_info.go, firewall/request_logger.go, firewall/rule_enforcer.go, session/context.go, session/server.go, session_rpcserver.go
Currently, in our RPC interceptors, we use the macaroon data in the request to extract the session ID. This is not ideal since we are using the root key ID of the macaroon and this can cause issues because sometimes we also store the first 4 bytes of an account ID in there. Or it could just be a totally unrelated macaroon that happens to have root key ID that matches with one of our session IDs. 
We should instead use a much more reliable way of passing along session ID info: we can do this because any request that comes in via a session, we can intercept and add the session ID to the grpc metadata for the call via the context. This will then be included in the ctx info that LND gets when which interceptors to send the request too. So LND can then send this metadata info _back_ to lit via …
=> multi: extract session ID from context

.github/workflows/main.yml, .gitignore, Makefile, go.mod, go.sum, itest/assets_test.go, itest/litd_custom_channels_test.go, itest/litd_node.go, itest/litd_test.go, itest/litd_test_list_on_test.go, itest/network_harness.go, itest/test_harness.go, scripts/install-backward-compat-versions.sh
Shows that https://github.com/lightninglabs/taproot-assets/pull/1537 restores backward compatibility.
=> custom channels: add itest to demonstrate that backward compatibility with v0.14.1-alpha is restored

.gitignore, accounts/sql_migration.go, accounts/sql_migration_test.go, accounts/test_kvdb.go, accounts/test_postgres.go, accounts/test_sqlite.go, db/sqlc/accounts.sql.go, db/sqlc/queries/accounts.sql, go.mod
This PR introduces the migration logic for transitioning the accounts store from kvdb to SQL.
Note that as of this PR, the migration is not yet triggered by any production code, i.e. only tests execute the migration logic.
Part of https://github.com/lightninglabs/lightning-terminal/issues/917
=> [sql-32] accounts: add migration code from kvdb to SQL

cmd/litcli/ln.go, docs/release-notes/release-notes-0.14.2.md
Uses the existing LND arguments for sat/msat amount for the `litcli ln addinvoice` command. This new argument exposes the behavior introduced in https://github.com/lightninglabs/taproot-assets/pull/1448
Closes https://github.com/lightninglabs/lightning-terminal/issues/1073
=> Use sat/msat arguments of `ln addinvoice`

scripts/check-go-version-dockerfile.sh, scripts/check-go-version-yaml.sh
Fixes the linter locally when itests were previously run (which now checks out backward compatible earlier versions of litd which might not conform to the linter's version check).
=> scripts: exclude backward compatible versions from linter

accounts/interceptor.go, config_dev.go, config_prod.go, firewall/request_info.go, firewall/request_logger.go, firewalldb/actions.go, firewalldb/actions_kvdb.go, firewalldb/actions_test.go, firewalldb/interface.go, firewalldb/kvdb_store.go, firewalldb/kvstores_test.go, firewalldb/test_kvdb.go
In this PR, we add best effort logic to ensure tight coupling between actions and sessions&accounts at the
time of action creation. This forces us to update our tests to expect certain errors if linked sessions/accounts
do not yet exist at the time of action creation. This sets us up nicely for the SQL impl of the actions DB which will
enforce strict coupling.
Part of #917
=> [sql-38] multi: couple sessions and accounts to actions

dev.Dockerfile
We can now use the `LND_VERSION` build argument to force a specific LND version to be used when building. If the `LND_VERSION` build argument is not set, then build continues as before this change and uses the version already defined in `go.mod` and `go.sum`.
=> dev.Dockerfile: allow forcing an lnd version

dev.Dockerfile
We can now use the `TAPRPC_VERSION` build argument to force a specific taprpc version to be used when building. If the `TAPRPC_VERSION` build argument is not set, then build continues as before this change and uses the version already defined in `go.mod` and `go.sum`.
=> dev.Dockerfile: allow forcing a taprpc version

db/sqlc/kvstores.sql.go, db/sqlc/migrations/000003_kvstores.up.sql, db/sqlc/models.go, db/sqlc/querier.go, db/sqlc/queries/kvstores.sql, firewalldb/actions_test.go, firewalldb/db.go, firewalldb/interface.go, firewalldb/kvstores_kvdb.go, firewalldb/kvstores_sql.go, firewalldb/sql_migration.go, firewalldb/sql_migration_test.go, firewalldb/test_kvdb.go, firewalldb/test_postgres.go, firewalldb/test_sql.go, firewalldb/test_sqlite.go
Based on #1051 
This PR introduces the migration logic for transitioning the kv stores from kvdb to SQL.
Note that as of this PR, the migration is not yet triggered by any production code, i.e. only tests execute the migration logic.
Once #1051 is merged, I will rebase this PR and request reviews.
Part of https://github.com/lightninglabs/lightning-terminal/issues/917
=> [sql-41] firewalldb: add migration code for kvstores from kvdb to SQL

session/sql_migration.go
Addresses the CI flake first discovered in #1126, run:
https://github.com/lightninglabs/lightning-terminal/actions/runs/16777826198/job/47508140669
In the kvdb to sql migration, if there have been caveats set for the MacaroonRecipe, the order of the postgres db caveats will in very rare cases differ from the kv store caveats. Therefore, we sort both the kv and sql caveats by their ID, so that we can compare them in a deterministic way.
I tried creating a deterministic test that triggers this issue, but wasn't successful. The best semi deterministic way to trigger this that I've found is to increased the number of sessions in the `randomizedSessions` test to high number like 5000, and then run this on a postgres backend. That triggers the issue most of the times.
@ellemouton & …
=> [sql-48] session: sort MacaroonRecipe.caveats in migration

session/sql_migration.go, session/sql_migration_test.go
The logic to avoid duplicate session IDs was first added with the session linking linking functionality. That means that there may be old legacy sessions that were added prior to that which may have duplicate IDs. Before this commit, such sessions would cause the kvdb to SQL migration to error, as there is a uniqueness constraint on the legacy session alias in the SQL sessions table.
We want to keep that constraint, so in such rare cases, we update the kvdb to SQL migration logic to drop all but the session with the latest CreatedAt time if for sessions that share the same ID.
That follows the logic in c8b78bd10dd5fee9cb250edc91229aa05d824877 as closely as possible, as that migration ensured that all sessions but the latest one was revoked if multiple sessions shared the same ID.
=> [sql-50] session migration duplicate ID fix

session/sql_migration.go, session/sql_migration_test.go
This PR fixes a edge case in the sessions migration, which was found during the creation of the actions migration.
If a user creates a session linked to an account, but later deletes that account using the `litcli accounts remove` command, the KVDB session will still contain the account ID of the removed account.
During the KVDB to SQL migration, the accounts migration runs before the sessions migration. Since the deleted account no longer exists, it cannot be migrated. As a result, the migrated SQL session cannot link to the now non-existent account in the SQL store.
In such cases, we will migrate the session and not link to any account in the SQL session.
=> [sql-51] session: handle removed linked account

firewall/request_logger.go, firewalldb/actions.go, firewalldb/actions_kvdb.go, firewalldb/actions_sql.go, firewalldb/actions_test.go, firewalldb/test_kvdb.go, session_rpcserver.go
Part of https://github.com/lightninglabs/lightning-terminal/issues/917
This PR addresses an issue I noticed we need to address prior to https://github.com/lightninglabs/lightning-terminal/pull/1143:
When migrating the actions store from kvdb to sql, we will need to update the existing actions to include the full mac root key, instead of just the last 4 bytes (currently called `MacaroonIdentifier`). In order to do so, we need to change the sql implementation of the `actions` store to persist the full mac root key, instead of just the last 4 bytes. As no production data in the sql actions store exists for users yet, it's fine for us to change this without having to address old sql actions which only stored the last 4 bytes.
This PR adds this change.
Note though that  this PR doesn't update …
=> [sql-53] firewalldb: actions migration prep 2 - persist full macaroon root key ID in the SQL actions store
