lightninglabs/lightning-terminal

go.mod, go.sum, terminal.go
Fixes https://github.com/lightninglabs/lightning-terminal/issues/110.
This also updates `loop` to `v0.8.1` and `lndclient` to `v0.11.0-0`.
=> Wait for lnd to be synced before starting subservers

README.md
Updates to the README:
- Added daemon versions for v0.1.1-alpha
- Added info about executing CLI commands
- Removed section headers from `lnd.conf` file
=> doc: update README doc

README.md, doc/compile.md, doc/config-lnd-remote.md, doc/remote.md, doc/troubleshooting.md
Updated README and added a few other docs. This PR closes #123
=> Simplified readme

Makefile, app/src/api/loop.ts, go.mod, go.sum, proto/loop.proto
Results in this user agent string being sent from LiT:
`litd/v0.11.1-beta/commit=v0.11.1-beta,initiator=lit-ui`
=> Loop user agent initiator

README.md, go.mod, go.sum
Updates Pool to `v0.3.4-alpha`.
=> Update Pool to v0.3.4-alpha

README.md
Preview for release notes:
- Allow an additional non-TLS listening address to be specified for use with Tor hidden services: #163.
=> README: update to v0.3.4-alpha

README.md, doc/config-lnd-integrated.md, doc/config-lnd-remote.md, doc/letsencrypt.md, doc/remote.md, doc/troubleshooting.md
=> docs: multiple small fixes

README.md
LiT links to this after installing.
=> Adding link for detailed instructions

app/src/Routes.tsx, app/src/components/layout/NavMenu.tsx, app/src/components/settings/SettingsPage.tsx, app/src/config.ts, app/src/store/store.ts, app/src/store/views/appView.ts
=> Use PUBLIC_URL throughout the app

README.md, app/src/types/generated/auctioneerrpc/auctioneer_pb.d.ts, app/src/types/generated/auctioneerrpc/auctioneer_pb.js, app/src/types/generated/trader_pb.d.ts, app/src/types/generated/trader_pb.js, app/src/util/tests/sampleData.ts, go.mod, go.sum, proto/auctioneerrpc/auctioneer.proto, proto/trader.proto, session/tlv_test.go, tools.go
With this commit we update the version of the Pool trader daemon to
v0.5.4-alpha. And we prepare the README for a new release of LiT
v0.6.2-alpha.
=> mod+app: bump Pool version to v0.5.4-alpha, prepare for release 0.6.2

Makefile, README.md, itest/litd_mode_integrated_test.go, itest/litd_mode_remote_test.go, rpc_proxy.go, terminal.go, version.go
Fixes https://github.com/lightninglabs/lightning-terminal/issues/329.
Fixes https://github.com/lightninglabs/lightning-terminal/issues/328.
=> Fix loop/pool over LNC in remote lnd mode, add version string

cmd/litcli/main.go
=> litcli: add app version

app/src/components/tour/WelcomeStep.tsx
Update broken link to walkthrough in WelcomeStep.tsx
=> Update broken link to walkthrough

.github/workflows/main.yml, Makefile, accounts/checkers.go, accounts/interceptor.go, go.mod, rpcmiddleware/interface.go, rpcmiddleware/interface_test.go, rpcmiddleware/proto.go
depends on :
- https://github.com/lightninglabs/lightning-terminal/pull/363
- https://github.com/lightningnetwork/lnd/pull/6630
=> multi: use the ability to intercept rpc requests and errors

app/src/components/theme.tsx
ui+theme: patch theme color bug introduced in #404
=> ui+theme: patch theme color

README.md, go.mod, go.sum, version.go
Bump integrated LND version to v0.15.4-beta & bump the LiT version to v0.8.3-alpha
=> multi: lit-v0.8.3-alpha

.github/workflows/main.yml, scripts/check-commit.sh, scripts/check-each-commit.sh
Add a check to github actions to check that each commit in a PR compiles
=> github+scripts: check commits compile

doc/config-lnd-remote.md, doc/remote.md
Add rpcmiddleware.enable=true as a needed config for the remote lnd node
#492
=> Add rpcmiddleware config for remote lnd instance

subservers/taproot-assets.go
Register the taproot-assets universe gRPC and REST servers.
=> subservers: register taproot assets universe servers

README.md, app/src/types/generated/loop_pb.d.ts, app/src/types/generated/loop_pb.js, app/src/types/generated/swapserverrpc/server_pb.d.ts, app/src/types/generated/swapserverrpc/server_pb.js, go.mod, go.sum, proto/loop.proto, proto/swapserverrpc/server.proto, version.go
This commit updates the integrated Loop version to v0.26.1-beta and
bumps Lit's version to v0.10.5-alpha
=> version+README: update LiT and Loop versions

config.go, docs/release-notes/release-notes-0.13.3.md
Fixes #798 by specifying what is running on the main litd HTTPS port.
=> config: update description of --httpslisten flag

rpc_proxy.go
Found a typo in a comment while checking the code.
=> rpc_proxy: fix typo

README.md
Updating per this issue https://github.com/lightninglabs/lightning-terminal/issues/834
=> Update README.md for taproot-assets-mode

go.mod, go.sum
This is a PR to update the lnc dependency and to test compatibility.
Todo:
=> mod: update lnc dependency

go.mod, go.sum
=> mod: pin litrpc version, bump protobuf-go-hex-display replaced version

docs/WALKTHROUGH.md, docs/accounts.md, docs/config-lnd-integrated.md
Hello
I fixed several spelling issues
Br, Elias.
=> docs fix spelling issues

README.md, docs/release-notes/release-notes-0.14.1.md, go.mod, go.sum, itest/assets_test.go, itest/litd_custom_channels_test.go, itest/litd_test_list_on_test.go, terminal.go, version.go
Update the integrated daemons to the latest RCs.
=> Update tapd and lnd, bump version to v0.14.1-alpha.rc2

README.md, app/src/types/generated/lnd_pb.d.ts, app/src/types/generated/lnd_pb.js, docs/release-notes/release-notes-0.14.1.md, go.mod, go.sum, proto/lnd.proto, version.go
Prepares everything for the release of the final `v0.14.1-alpha` version.
=> release: v0.14.1-alpha final

go.mod, go.sum
Fixes: https://github.com/lightninglabs/lightning-terminal/issues/1021
Depends on: https://github.com/lightningnetwork/lnd/pull/9665
=> buld: bump kvdb mod version

itest/litd_custom_channels_test.go
remove duplicate package imports
=> chore: remove duplicate package imports
